### ISSUE TITLE
Unable to find a specification for AdTrace

### ISSUE THREAD

**Issue by amereii** [adtrace/adtrace_sdk_react_native#2]
After fixing https://github.com/adtrace/adtrace_sdk_react_native/pull/1
When I run `pod install` again , I have the following error

```
[!] Unable to find a specification for `AdTrace (~> 1.0.3)` depended upon by `react-native-adtrace`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

@arefhosseini How can I fix it? why I am unable to find `AdTrace` pod ?

**Comment by amereii** [comment]
https://github.com/adtrace/adtrace_sdk_react_native/blob/c15070b7c1a90fed91cc2f5a8e97cb46808b4081/react-native-adtrace.podspec#L21


Why there is no `AdTrace` package in cocoapods?

![image](https://user-images.githubusercontent.com/16239920/72340334-4914e580-36dd-11ea-95c7-cdfa7990232d.png)

**Comment by arefhosseini** [comment]
Hey, thanks for pointing Adtrace in `pod`.
Actually we are creating and testing Adtrace for `cocoapods` and `react native`.
It will be ready for next update.
Thanks for your patient.

**Comment by arefhosseini** [comment]
Version of iOS SDK fixed now.
Thanks for mention that.

**Comment by amereii** [comment]
@arefhosseini Thanks
Just release a new `react-native-adtrace` version in NPM

**Comment by arefhosseini** [comment]
released `v1.0.8`.

**Comment by amereii** [comment]
@arefhosseini it is not fixed yet
Please try it yourself after installing `v1.0.8` and running `pod install`

```
[!] Unable to find a specification for `AdTrace (~> 1.0.1)` depended upon by `react-native-adtrace`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```
